pipeline:
  trigger: null
  event:
    include:
      - pull_request
      - push
      - tag
  name: 1b
  identifier: b
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: 1b
        identifier: b
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: 1b
                  identifier: b
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
