name: Setup Go on PR
on:
  pull_request:
    branches:
      - main
jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.18'
      - name: Verify Go installation
        run: go version
